package com.exobe.entity.response

import com.google.gson.annotations.SerializedName
class PaymentFromCustomer(
    @SerializedName("result") val result : PaymentFromCustomer_Result,
    @SerializedName("responseMessage") val responseMessage : String,
    @SerializedName("responseCode") val responseCode : Int
)
class PaymentFromCustomer_Result(
    @SerializedName("docs") val docs : List<PaymentFromCustyomer_Docs>,
    @SerializedName("total") val total : Int,
    @SerializedName("limit") val limit : Int,
    @SerializedName("page") val page : Int,
    @SerializedName("pages") val pages : Int
)
class PaymentFromCustyomer_Docs(
//    @SerializedName("_id") val _id : String,
//    @SerializedName("status") val status : String,
//    @SerializedName("transactionStatus") val transactionStatus : String,
//    @SerializedName("transactionDetails") val transactionDetails : PaymentFromCustomer_TransactionDetails,
//    @SerializedName("userId") val userId : String,
    @SerializedName("orderId") val orderId : String,
//    @SerializedName("transactionMethod") val transactionMethod : String,
    @SerializedName("orderAmount") val orderAmount : Number,
//    @SerializedName("shippingAddress") val shippingAddress : String,
//    @SerializedName("currencyCode") val currencyCode : String,
    @SerializedName("createdAt") val createdAt : String,
//    @SerializedName("updatedAt") val updatedAt : String,
//    @SerializedName("__v") val __v : Int,
    @SerializedName("userDetails") val userDetails : PaymentFromCustyomerUserDetails,
    @SerializedName("orderDetails") val orderDetails : PaymentFromCustyomer_OrderDetails,
//    @SerializedName("orders") val orders : List<PaymentFromCustyomer_Order>,
    @SerializedName("PaidToDetails") val paidToDetails : List<PaymentFromCustyomer_PaidToDetails>
)
class PaymentFromCustyomer_OrderDetails(
//    @SerializedName("_id") val _id : String,
//    @SerializedName("taxPrice") val taxPrice : Int,
//    @SerializedName("dealId") val dealId : List<String>,
//    @SerializedName("orderStatus") val orderStatus : String,
//    @SerializedName("deliveryStatus") val deliveryStatus : String,
//    @SerializedName("paymentStatus") val paymentStatus : String,
//    @SerializedName("status") val status : String,
//    @SerializedName("userId") val userId : String,
//    @SerializedName("serviceDetails") val serviceDetails : List<ServiceDetails>,
//    @SerializedName("orderPrice") val orderPrice : Int,
//    @SerializedName("actualPrice") val actualPrice : Int,
    @SerializedName("orderId") val orderId : String,
//    @SerializedName("orderType") val orderType : String,
//    @SerializedName("productDetails") val productDetails : List<String>,
//    @SerializedName("createdAt") val createdAt : String,
//    @SerializedName("updatedAt") val updatedAt : String,
//    @SerializedName("__v") val __v : Int,
//    @SerializedName("shippingAddress") val shippingAddress : String,
//    @SerializedName("services") val services : List<PaymentFromCustyomer_Services>
)
class PaymentFromCustyomer_Order(
//    @SerializedName("_id") val _id : String,
//    @SerializedName("serviceLocation") val serviceLocation : ServiceLocation,
//    @SerializedName("serviceImage") val serviceImage : List<String>,
//    @SerializedName("slots") val slots : List<String>,
//    @SerializedName("status") val status : String,
//    @SerializedName("categoryId") val categoryId : String,
//    @SerializedName("subCategoryDetails") val subCategoryDetails : List<SubCategoryDetails>,
//    @SerializedName("userId") val userId : String,
//    @SerializedName("__v") val __v : Int,
//    @SerializedName("createdAt") val createdAt : String,
//    @SerializedName("updatedAt") val updatedAt : String

)
class PaymentFromCustyomer_PaidToDetails(
//    @SerializedName("_id") val _id : String,
//    @SerializedName("storeLocation") val storeLocation : StoreLocation,
//    @SerializedName("businessDetails") val businessDetails : BusinessDetails,
//    @SerializedName("businessBankingDetails") val businessBankingDetails : BusinessBankingDetails,
//    @SerializedName("serviceDetails") val serviceDetails : ServiceDetails,
//    @SerializedName("address") val address : String,
//    @SerializedName("otpVerification") val otpVerification : Boolean,
//    @SerializedName("userVerification") val userVerification : Boolean,
//    @SerializedName("profilePic") val profilePic : String,
//    @SerializedName("websiteUrl") val websiteUrl : String,
//    @SerializedName("duration") val duration : String,
//    @SerializedName("userRequestStatus") val userRequestStatus : String,
//    @SerializedName("zipCode") val zipCode : Int,
//    @SerializedName("eoriNumber") val eoriNumber : Int,
//    @SerializedName("additionalDocName") val additionalDocName : String,
//    @SerializedName("additionalDocument") val additionalDocument : String,
//    @SerializedName("ownerFirstName") val ownerFirstName : String,
//    @SerializedName("ownerLastName") val ownerLastName : String,
//    @SerializedName("ownerEmail") val ownerEmail : String,
//    @SerializedName("noOfUniqueProducts") val noOfUniqueProducts : Int,
//    @SerializedName("listOfBrandOrProducts") val listOfBrandOrProducts : List<String>,
//    @SerializedName("keepStock") val keepStock : Boolean,
//    @SerializedName("isPhysicalStore") val isPhysicalStore : Boolean,
//    @SerializedName("preferredSupplierOrWholeSalerId") val preferredSupplierOrWholeSalerId : List<String>,
//    @SerializedName("comments") val comments : String,
//    @SerializedName("completeProfile") val completeProfile : Boolean,
//    @SerializedName("flag") val flag : Int,
//    @SerializedName("placeOrderCount") val placeOrderCount : Int,
//    @SerializedName("serviceOrderCount") val serviceOrderCount : Int,
//    @SerializedName("receiveOrderCount") val receiveOrderCount : Int,
//    @SerializedName("status") val status : String,
//    @SerializedName("userType") val userType : String,
    @SerializedName("firstName") val firstName : String,
    @SerializedName("lastName") val lastName : String,
//    @SerializedName("countryCode") val countryCode : Int,
//    @SerializedName("mobileNumber") val mobileNumber : Int,
//    @SerializedName("email") val email : String,
//    @SerializedName("phoneNumber") val phoneNumber : Int,
//    @SerializedName("socialLink") val socialLink : SocialLink,
//    @SerializedName("password") val password : String,
//    @SerializedName("govtDocument") val govtDocument : GovtDocument,
//    @SerializedName("city") val city : String,
//    @SerializedName("state") val state : String,
//    @SerializedName("country") val country : String,
//    @SerializedName("addressLine1") val addressLine1 : String,
//    @SerializedName("addressLine2") val addressLine2 : String,
//    @SerializedName("createdAt") val createdAt : String,
//    @SerializedName("updatedAt") val updatedAt : String,
//    @SerializedName("__v") val __v : Int,
//    @SerializedName("businessDocumentUpload") val businessDocumentUpload : BusinessDocumentUpload,
//    @SerializedName("userUniqueId") val userUniqueId : String,
//    @SerializedName("isReset") val isReset : Boolean
)
class PaymentFromCustyomer_Services(
//    @SerializedName("_id") val _id : String,
//    @SerializedName("serviceLocation") val serviceLocation : ServiceLocation,
//    @SerializedName("serviceImage") val serviceImage : List<String>,
//    @SerializedName("slots") val slots : List<String>,
//    @SerializedName("status") val status : String,
//    @SerializedName("categoryId") val categoryId : String,
//    @SerializedName("subCategoryDetails") val subCategoryDetails : List<SubCategoryDetails>,
//    @SerializedName("userId") val userId : String,
//    @SerializedName("__v") val __v : Int,
//    @SerializedName("createdAt") val createdAt : String,
//    @SerializedName("updatedAt") val updatedAt : String
)
data class PaymentFromCustyomerUserDetails (

//    @SerializedName("_id") val _id : String,
//    @SerializedName("storeLocation") val storeLocation : StoreLocation,
//    @SerializedName("businessDetails") val businessDetails : BusinessDetails,
//    @SerializedName("businessBankingDetails") val businessBankingDetails : BusinessBankingDetails,
//    @SerializedName("serviceDetails") val serviceDetails : ServiceDetails,
//    @SerializedName("address") val address : String,
//    @SerializedName("otpVerification") val otpVerification : Boolean,
//    @SerializedName("userVerification") val userVerification : Boolean,
//    @SerializedName("profilePic") val profilePic : String,
//    @SerializedName("websiteUrl") val websiteUrl : String,
//    @SerializedName("duration") val duration : String,
//    @SerializedName("userRequestStatus") val userRequestStatus : String,
//    @SerializedName("zipCode") val zipCode : Int,
//    @SerializedName("eoriNumber") val eoriNumber : String,
//    @SerializedName("additionalDocName") val additionalDocName : String,
//    @SerializedName("additionalDocument") val additionalDocument : String,
    @SerializedName("ownerFirstName") val ownerFirstName : String,
    @SerializedName("ownerLastName") val ownerLastName : String,
//    @SerializedName("ownerEmail") val ownerEmail : String,
//    @SerializedName("noOfUniqueProducts") val noOfUniqueProducts : Int,
//    @SerializedName("listOfBrandOrProducts") val listOfBrandOrProducts : List<String>,
//    @SerializedName("keepStock") val keepStock : Boolean,
//    @SerializedName("isPhysicalStore") val isPhysicalStore : Boolean,
//    @SerializedName("preferredSupplierOrWholeSalerId") val preferredSupplierOrWholeSalerId : List<String>,
//    @SerializedName("comments") val comments : String,
//    @SerializedName("completeProfile") val completeProfile : Boolean,
//    @SerializedName("flag") val flag : Int,
//    @SerializedName("placeOrderCount") val placeOrderCount : Int,
//    @SerializedName("serviceOrderCount") val serviceOrderCount : Int,
//    @SerializedName("receiveOrderCount") val receiveOrderCount : Int,
//    @SerializedName("status") val status : String,
//    @SerializedName("userType") val userType : String,
    @SerializedName("firstName") val firstName : String,
    @SerializedName("lastName") val lastName : String,
//    @SerializedName("countryCode") val countryCode : Int,
//    @SerializedName("mobileNumber") val mobileNumber : Int,
//    @SerializedName("email") val email : String,
//    @SerializedName("phoneNumber") val phoneNumber : String,
//    @SerializedName("storeAddress") val storeAddress : String,
//    @SerializedName("storeName") val storeName : String,
//    @SerializedName("password") val password : String,
//    @SerializedName("city") val city : String,
//    @SerializedName("country") val country : String,
//    @SerializedName("addressLine1") val addressLine1 : String,
//    @SerializedName("addressLine2") val addressLine2 : String,
//    @SerializedName("createdAt") val createdAt : String,
//    @SerializedName("updatedAt") val updatedAt : String,
//    @SerializedName("__v") val __v : Int,
//    @SerializedName("otp") val otp : Int,
//    @SerializedName("otpExpireTime") val otpExpireTime : Int,
//    @SerializedName("isReset") val isReset : Boolean,
//    @SerializedName("userUniqueId") val userUniqueId : String,
//    @SerializedName("businessDocumentUpload") val businessDocumentUpload : BusinessDocumentUpload
)

data class PaymentFromCustomer_TransactionDetails (

    @SerializedName("id") val id : String,
//    @SerializedName("object") val object : String,
    @SerializedName("amount") val amount : Int,
    @SerializedName("amount_captured") val amount_captured : Int,
    @SerializedName("amount_refunded") val amount_refunded : Int,
    @SerializedName("application") val application : String,
    @SerializedName("application_fee") val application_fee : String,
    @SerializedName("application_fee_amount") val application_fee_amount : String,
    @SerializedName("balance_transaction") val balance_transaction : String,
//    @SerializedName("billing_details") val billing_details : Billing_details,
    @SerializedName("calculated_statement_descriptor") val calculated_statement_descriptor : String,
    @SerializedName("captured") val captured : Boolean,
    @SerializedName("created") val created : Int,
    @SerializedName("currency") val currency : String,
    @SerializedName("customer") val customer : String,
    @SerializedName("description") val description : String,
    @SerializedName("destination") val destination : String,
    @SerializedName("dispute") val dispute : String,
    @SerializedName("disputed") val disputed : Boolean,
    @SerializedName("failure_balance_transaction") val failure_balance_transaction : String,
    @SerializedName("failure_code") val failure_code : String,
    @SerializedName("failure_message") val failure_message : String,
    @SerializedName("invoice") val invoice : String,
    @SerializedName("livemode") val livemode : Boolean,
    @SerializedName("on_behalf_of") val on_behalf_of : String,
    @SerializedName("order") val order : String,
//    @SerializedName("outcome") val outcome : Outcome,
    @SerializedName("paid") val paid : Boolean,
    @SerializedName("payment_intent") val payment_intent : String,
    @SerializedName("payment_method") val payment_method : String,
//    @SerializedName("payment_method_details") val payment_method_details : Payment_method_details,
    @SerializedName("receipt_email") val receipt_email : String,
    @SerializedName("receipt_number") val receipt_number : String,
    @SerializedName("receipt_url") val receipt_url : String,
    @SerializedName("refunded") val refunded : Boolean,
//    @SerializedName("refunds") val refunds : Refunds,
    @SerializedName("review") val review : String,
    @SerializedName("shipping") val shipping : String,
//    @SerializedName("source") val source : Source,
    @SerializedName("source_transfer") val source_transfer : String,
    @SerializedName("statement_descriptor") val statement_descriptor : String,
    @SerializedName("statement_descriptor_suffix") val statement_descriptor_suffix : String,
    @SerializedName("status") val status : String,
    @SerializedName("transfer_data") val transfer_data : String,
    @SerializedName("transfer_group") val transfer_group : String
)